exclude: '.git|.tox|.trash'
default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: mpinterfaces_setup.py


  - repo: https://github.com/asottile/pyupgrade
    rev:  v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.3.0]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [--py310-plus]
      # - id: nbqa-isort
      - id: nbqa-flake8
        args: [--ignore=E402]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies:
          - flake8-isort
          - flake8-builtins
          # - flake8-docstrings

  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: 'v1.8.0'  # Use the sha / tag you want to point at
  #     hooks:
  #     -   id: mypy
  #         verbose: True
  #         additional_dependencies: ['types-PyYAML', 'types-requests']
  #         entry: bash -c 'mypy "$@" || true' --
